DROP TABLE IF EXISTS assignment;
DROP TABLE IF EXISTS provider_location;
DROP TABLE IF EXISTS patient;
DROP TABLE IF EXISTS tenant;
DROP EXTENSION IF EXISTS btree_gist;
DROP EXTENSION IF EXISTS postgis;
